### ISSUE TITLE
Unable to contact via Slack

### ISSUE THREAD

**Issue by dpshelio** [ctlearn-project/ctlearn#106]
A slack team is mentioned on the [Open Astronomy](http://openastronomy.org/members/) page. However, there's no way to generate an auto-invitation for it.

Alternatively, it would be appreciated if some mentor/admin is in the OpenAstronomy room as few students have come asking for help or how to contact someone in the team.

**Comment by lightningedge007a** [comment]
I would be delighted if I can have a more direct way to contact the mentors. There is a lot I want to discuss on the project ROOT Input and get feedback on my proposal.

**Comment by TjarkMiener** [comment]
Hey @dpshelio! Thanks for opening this issue to clarify things for the GSoC students! We chose to interact with the GSoC students via our GitHub issues, since this is the main tool Open Astronomy is using for communication. I also posted my email (tmiener@ucm.es) in some GitHub issues, in case the students want to have some feedback for their application draft. This communication way worked out for the major part of the students so far.

**Comment by aribrill** [comment]
Thanks @dpshelio. What's the main communication room for OpenAstronomy? Is it the Google group, Slack, or something else?

**Comment by Juanlu001** [comment]
@aribrill (answering for @dpshelio) most students arrive through the [OpenAstronomy chat on Matrix](https://chat.openastronomy.org/#/room/#openastronomy:openastronomy.org).

**Comment by lightningedge007a** [comment]
@aribrill @qi-feng @rlopezcoto , I have emailed you a draft of my proposal. Please suggest necessary changes so I apply them quickly. 
Thank You.
