### ISSUE TITLE
Random predictions when path to checkpoints not found

### ISSUE THREAD

**Issue by TjarkMiener** [ctlearn-project/ctlearn#123]
When you run in predict mode and the path of your checkpoints not exist, CTLearn will predict randomly. It should break and tell the user that the checkpoints are not found.

**Comment by ayushvpaliwal** [comment]
Hello,
My name is Ayush Paliwal, a sophomore student at Indian Institute Of Technology, IIT(BHU), Varanasi. I am an open-source enthusiast, and Astronomy is my passion. I am particularly interested in this project. I would love to contribute to this project during GSOC 2020 and further and learn a bunch of things on the way.
Here, I would like to share my views on this issue.

**Comment by ayushvpaliwal** [comment]
Sometimes the path of the checkpoint doesn't exist, or the size of a variable in model changes or we add or remove a variable, the Estimator cannot load an existing checkpoint any more. Then evolution runs with newly initialized Variables instead of ones restored from checkpoint and results in random predictions.

Possible solution is that (1). Be able to load an existing checkpoint from a different path than the Estimator's model_dir when there is no checkpoint in the model_dir yet. This is helpful to start training from a different checkpoint without manually having to copy those model's checkpoints into the new model_dir. (2). Specify the flag that may say that " cant load variables and so no prediction".

We are using a custom estimator in CTlearn, and supplying our own model_fn, so we can call init_from_checkpoint. The checkpoint_dir arg can be different from our model_dir, and assignment_map allows us to map only the subset of variables we want to load. And if we do not allow to load any variable here, then we can stop random prediction.

**Comment by TjarkMiener** [comment]
Hi @ayushvpaliwal, Thanks for your input on this issue!
I solved that issue in [71299f3](https://github.com/ctlearn-project/ctlearn/commit/71299f3cc0ed11973bce201a56dc316345cee0d5). Does this makes sense to you? If we run ctlearn in 'predict' mode and we can't find the model_dir the code should crash. We will be merging this branch to the master soon.

For clarification: When we run ctlearn in 'train' mode, we are doing what you described above (more or less). It's worth having a look at the CTLearn models in the default_models folder.
