### ISSUE TITLE
Map images from all IACT observatories

### ISSUE THREAD

**Issue by aribrill** [ctlearn-project/ctlearn#60]
ImageMapper should include a mapping table for at least the following telescopes, in addition to the ones already implemented. This could be done working with people from the relevant observatories. FACT and H.E.S.S. are included in [ctapipe](https://github.com/cta-observatory/ctapipe-extra/tree/master/ctapipe_resources), though I don't see a camera geometry file for MAGIC.

- [x] FACT
- [x] HESS-I
- [x] HESS-II
- [x] MAGIC

**Comment by TjarkMiener** [comment]
**Comment referring to the implementation of the MAGIC camera:**

Last week @nietootein and me was working on the implementation of the MAGIC camera. We faced a few problem, which i will described in the following. Lab (MAGICian, who attended CTLearn calls in the past) provided us with a file containing the pixel position for each index and the configuration information. To sum it up, the MAGIC cameras are very similar to the VERITAS cameras. The first index mark the center of the camera. Then there are 19 spirals, where the three outermost spirals are not fully populated with pixels. The MAGIC camera is rotated by 19.0° (Lab couldn't tell me why), which caused the main problem in our implementation.

So, what have we done so far? 
1. We were able to create an image of the unrotated MAGIC camera using a modified version of the function `generate_table_VTS(self)` (image_mapping.py). We won't face any problem, if we are only using MAGIC data, because all events will be rotated with the same angle. But there might be problems with the direction estimation, when combining telescopes for analyses. Right?
![mgc_camera_unrotated](https://user-images.githubusercontent.com/37835610/46248425-7ae73780-c419-11e8-86dc-6ce3b8516942.png)
![vts_camera](https://user-images.githubusercontent.com/37835610/46248467-da454780-c419-11e8-9a82-0c2b78eaf8a7.png)
2. We took the file from Lab and converted into MGC_pos.npy file like the other files in /ctlearn/pixel_pos_files. Using the function `generate_table_generic(self, tel_type, pixel_weight=1.0/4)` (image_mapping.py) we created a weird image of the MAGIC camera, where pixels overlap. Reducing the pixel_length by the half and extending the output image dimension, solved the overlapping, but added some gaps between the pixels. However, the gaps will be the same for all MAGIC events. At the end of the day, it won't add any bias in our classification. Or am I wrong?
![mgc_camera_pixelposition](https://user-images.githubusercontent.com/37835610/46248456-c7327780-c419-11e8-8942-a8aa1854d308.png)
![mgc_camera_pixelposition_extended](https://user-images.githubusercontent.com/37835610/46248460-cd285880-c419-11e8-9560-3e625af97061.png)
We also noticed that the LST camera is rotated. It's implemented with a pixel_pos_files as well. So the code is reading in the pixel position from the file and then apply the function `rotate_cam(self, pos)`, which rotate the camera about roughly 10°. In MAGIC the pixel position are already rotated by default. It would be nice, if the creator of the implementation of the LST and VERITAS camera could comment on this and help us. @qi-feng 

After the changes of @Jsevillamol in `map_image(self, pixels, telescope_type)` the notebook `ctlearn/notebooks/test_image_mapper.ipynb` isn't working. I will open a issue for that and assign myself, since I already fixed it in order to plot the MAGIC and VERITAS cameras.

Feel free to comment. Any kind of advice is more than welcome. Thank you.

**Comment by qi-feng** [comment]
You can create a rotate_MAGIC_cam function just like the rotate_cam method in ImageMapper class.
    def rotate_cam(self, pos):
        rotation_matrix = np.matrix([[0.98198181, 0.18897548],
                             [-0.18897548, 0.98198181]], dtype=float)
        pos_rotated = np.squeeze(np.asarray(np.dot(rotation_matrix, pos)))
        return pos_rotated

Note that you need to change the matrix to correctly reflect the 19-deg MAGIC rotation. LST/MST rotation angle may be different (hard coded in the function above). This is likely why your second set of images look wrong.

**Comment by TjarkMiener** [comment]
We implemented the FACT camera. Currently waiting for a confirmation of a FACT member.
![fact_camera](https://user-images.githubusercontent.com/37835610/46360665-356e7880-c66c-11e8-9816-2bba5b981a0a.png)
