### ISSUE TITLE
 Implementation of regression for energy and direction estimation

### ISSUE THREAD

**Issue by TjarkMiener** [ctlearn-project/ctlearn#67]
For a better IACT event reconstruction, it is necessary to implement regression for energy and direction estimation in CTLearn.

**Comment by JaiKotia** [comment]
@aribrill @TjarkMiener Hey what is the status on this issue? I see the data pipelining is being worked on through an API for DataLoader output. I was interested in taking up this project for GSoC 2019. Let me know if I could start contributing to the project. Also I couldn't find you guys on the Astropy slack channel.

**Comment by TjarkMiener** [comment]
We decided to implement the regression tasks using the approach of [Multi-Task Learning](http://ruder.io/multi-task/). A good start for all interested student would be to study this approach in detail and get familiar with the CTLearn models.

**Comment by parthpm** [comment]
I am interested in this project and gone through the above link.

**Comment by kaiyon07** [comment]
Hello Sir, I am interested in taking this project for GSOC-2019 and I have also completed reading about Multi-Task Learning. I also have deep learning background and very motivated about this project, kindly guide me through.
Thanks In Advance

**Comment by parthpm** [comment]
What's the next task after going through the above link?

**Comment by ABHIJIT-13** [comment]
hello, I am interested in contributing to the project regression under gsoc 2019. I have gone through the above link. Could you please guide me towards the next task. 
I am very much interested in this project and I believe my skill set matches the required ones.
I was unable to get in contact with the mentors as the no one in the gitter lobby knows the slackroom for the above project. 
Any help would be appreciated.
Thank you

**Comment by mrektor** [comment]
Hi, my name is Ettore Mariotti and I'm a graduating student in Telecommunication Enginnering (A MsC after a bachelor in Information Enginnering).
My recent passion is Machine Learning in general, I've had some experience both in data-scarce (Brain Computer Interfaces problems) and in data-rich situations (IACT MAGIC reconstruction with CNNs).

One of the most interesting aspect in partecipating in this program would be a full immersion on how to write good code in a collective project. I've usually coded always on my own, or in very restricted teams.
I would really appreciate to dive in some best practice about code writing in this environment.


These are my known computer languages:
1) Python - level: very good
2) Wolfram Mathematica - level: very good
3) MATLAB - level: good
4) C - level: medium

These are some python libraries which I have familiarity with:
1) Pandas
2) Numpy
3) Scipy
4) Scikit-Learn
5) Keras
6) Tensorflow 2.0
7) TPOT
8) tsfresh
9) Matplotlib


Since I've already developed some deep learning tools for the problem of gamma/hadron separation and for the reconstruction of energy and directions of the primary particles using regression techniques, I'm familiar with what it needs to be done and I'll just have to adapt to CTLearn library.

I would really love to give a contribute for this GSOC project

**Comment by TjarkMiener** [comment]
Dear @JaiKotia @parthpm @kaiyon07 @ABHIJIT-13 @mrektor,
@aribrill recently finished his work on the [DL1DH reader](https://github.com/cta-observatory/dl1-data-handler/blob/master/dl1_data_handler/reader.py). The next step for you would be to understand the implementation and get familiar with the usage of the reader. Besides that I found an interesting reference [here](https://towardsdatascience.com/multitask-learning-in-tensorflow-with-the-head-api-68f2717019df). However, for now your application should have the highest priority.

**Comment by kaiyon07** [comment]
@TjarkMiener Sir can I have your email id, I wanted my proposal to be reviewed.

**Comment by TjarkMiener** [comment]
Hi all @JaiKotia @parthpm @kaiyon07 @ABHIJIT-13 @mrektor,
In addition to your application you have to make a PR in CTLearn. This is a rule from GSoC; not from us! This PR don't have to contain any code for now! But any code you wrote is more than welcome and should be included! What have to be included is bascially a summary of your application! So just introduce yourself and sum up the project and your progress so far. Feel free to copy paste some parts of your application. Spent more time in your application than in the PR!

My email is tmiener@ucm.es in case you want to have some feedback for your application. Cheers!

**Comment by lightningedge007a** [comment]
Hi @aribrill , I am 3rd year, Computer Science, Bachelor of Technology student from Jaypee Institute of Information Technology. I found ROOT Input and Regression projects to be amazing and I want to pick them up for GSOC 2019. Can you please guide me on which one should I draft my proposal according to my skillset:
SKILLS
Machine Learning, Deep Learning, Artificial Intelligence, Data Analysis, Data Science,Natural Language Processing (NLP), Artificial Intelligence (AI),
Computer Vision, PyTorch, Keras, TensorFlow,
Python, Java, C/C++
Docker, Git, Google Colab, Amazon Web Services (AWS), Cloud Computing
PL/SQL, Object-Oriented Programming (OOP), Linux

my email: abhishekverma1610@gmail.com

**Comment by archisha-chandel** [comment]
Hi, I am interested in this project and I am a Computer Science student. I see that somethings have been done earlier in this particular issue. It would be really helpful if someone could guide me to get started with making contributions to this project?
