### ISSUE TITLE
Log both to console and to file by default

### ISSUE THREAD

**Issue by Jsevillamol** [ctlearn-project/ctlearn#83]
It felt really painful when I realized that I had forgotten to activate the log_to_dir option after 7 h of training.

Why are we not creating the log always?

**Comment by aribrill** [comment]
Sorry about that. I agree that the default behavior ought to be to both print to console and log to file. There could be a flag to disable console output, but a log should always be produced. Logging to console should be part of the default so that the default behavior produces output to show something is happening. A technical difficulty might be setting the logging output filestream to two locations, I'm not sure how hard that will be.

**Comment by TjarkMiener** [comment]
With CTLearn v0.6.X we are storing/plotting the training and validation metrics by default. So I think this issue is solved by the feature.
